name: Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  tests:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: MeiliSearch (latest) setup with Docker
      run: docker run -d -p 7700:7700 getmeili/meilisearch:latest ./meilisearch --master-key=masterKey --no-analytics=true
    - name: Run tests
      run: bundle exec rspec
    env:
      MEILISEARCH_HOST: http://localhost:7700
      MEILISEARCH_API_KEY: masterKey
